name: tf-deploy

on:
  push:
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'README.md'
      - '.gitignore'
      - '.gitmodules'
    branches: [ 'main' ]

  workflow_dispatch:

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

jobs:

  tf-quality-check:
    uses: ./.github/workflows/tf-quality-check.yml
    secrets: inherit

  deploy:
    needs: [tf-quality-check]
    runs-on: ubuntu-latest
    if: needs.tf-quality-check.result == 'success'

    steps:
      - uses: actions/checkout@v4

      - name: Generate next release number
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          dry_run: true